import { useState, useEffect } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import Sidebar from '../../components/Sidebar';
import StatusTimeline from '../../components/StatusTimeline';
import Modal from '../../components/Modal';
import api from '../../services/api';
import PaymentModal from '../../components/PaymentModal';


export default function DonorDashboard() {
  const { user } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  const [profile, setProfile] = useState(null);
  const [matches, setMatches] = useState([]);
  const [reports, setReports] = useState([]);
  const [selectedMatch, setSelectedMatch] = useState(null);
  const [loading, setLoading] = useState(true);
  const [showPayment, setShowPayment] = useState(false);

  useEffect(() => {
    const path = location.pathname.split('/').pop();
    if (path === 'reports') {
      document.getElementById('reports-section')?.scrollIntoView({ behavior: 'smooth' });
    } else if (path === 'matches') {
      document.getElementById('matches-section')?.scrollIntoView({ behavior: 'smooth' });
    }
  }, [location.pathname, loading]);

  useEffect(() => {
    const load = async () => {
      try {
        const [p, m, r] = await Promise.all([
          api.get('/donor/profile').catch(() => ({ data: null })),
          api.get('/matches/my-matches').catch(() => ({ data: [] })),
          api.get('/donor/reports').catch(() => ({ data: [] })),
        ]);
        setProfile(p.data);
        setMatches(m.data);
        setReports(r.data);
      } finally { setLoading(false); }
    };
    load();
  }, []);

  const downloadReport = (m) => {
    const content = `====================================================
               CLINICAL MATCH REPORT
====================================================
Match Record ID: #${m.id}
Current Status: ${m.status}
Compatibility Score: ${m.match_score}%

DONOR DETAILS:
-------------
Blood Type: ${profile?.blood_type || 'N/A'}
Organ Donated: ${profile?.organ_to_donate || 'N/A'}

RECIPIENT DETAILS:
-----------------
Name: ${m.recipient_name}
Contact: ${['Hospital Approved', 'In Progress', 'Completed'].includes(m.status) ? (m.recipient_email || 'hospital-registry@org.match') : 'Restricted pending hospital approval.'}

ADDITIONAL MATCH DATA:
---------------------
Match Created At: ${m.created_at ? new Date(m.created_at).toLocaleString() : 'N/A'}
Last Updated At: ${m.updated_at ? new Date(m.updated_at).toLocaleString() : 'N/A'}

This document is officially generated by the OrganMatch Registry System.
====================================================`;

    const dataStr = "data:text/plain;charset=utf-8," + encodeURIComponent(content);
    const downloadAnchorNode = document.createElement('a');
    downloadAnchorNode.setAttribute("href", dataStr);
    downloadAnchorNode.setAttribute("download", `Donor_Match_Report_${m.id}.txt`);
    document.body.appendChild(downloadAnchorNode);
    downloadAnchorNode.click();
    downloadAnchorNode.remove();
  };

  const handleGenerateMatches = null; // Removed for production flow

  if (loading) return <div className="dashboard-layout"><Sidebar /><div className="main-content"><div className="loading-spinner"><div className="spinner"></div><p>Loading dashboard...</p></div></div></div>;

  if (profile && !profile.is_paid) return (
    <div className="dashboard-layout"><Sidebar />
      <main className="main-content">
        <div style={{ maxWidth: '600px', margin: '4rem auto', textAlign: 'center' }}>
          <div className="card" style={{ padding: '3rem' }}>
            <div style={{ fontSize: '4rem', marginBottom: '1.5rem' }}>📑</div>
            <h2 className="mb-2">Report Verification Fee Required</h2>
            <p className="text-muted mb-6">To submit your clinical reports for hospital audit and enter the matching queue, a one-time verification fee of <strong>₹500</strong> is required.</p>
            <button className="btn btn-primary w-full" style={{ padding: '1rem' }} onClick={() => setShowPayment(true)}>Pay Verification Fee</button>
          </div>
        </div>
        <PaymentModal isOpen={showPayment} onClose={() => setShowPayment(false)} onSuccess={() => api.get('/donor/profile').then(res => setProfile(res.data))} amount={500} purpose="Clinical Report Verification Fee" />
      </main>
    </div>
  );

  return (
    <div className="dashboard-layout">
      <Sidebar />
      <main className="main-content">
        <div className="topbar">
          <div>
            <h1 style={{ color: 'var(--primary)' }}>Donor Dashboard</h1>
            <p className="text-muted">Clinical Registry & Match Management — Case ID: <strong>#{user?.id}</strong></p>
          </div>
          {/* Update Profile Button Removed as requested */}
        </div>

        {!profile && (
          <div className="alert alert-error">
             <h4 style={{ margin: 0 }}>Action Required: Profile Incomplete</h4>
             <p className="text-sm">Please register your medical details to enter the matching queue.</p>
             <button className="btn btn-sm btn-primary" style={{ marginTop: '1rem' }} onClick={() => navigate('/donor/register')}>Register Now</button>
          </div>
        )}

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '1.5rem', marginBottom: '3rem' }}>
          {[
            { label: 'Active Matches', val: matches.length, color: 'var(--primary)', bg: '#fff7ed', icon: '🤝' },
            { label: 'Verified Reports', val: reports.length, color: '#6366f1', bg: '#eef2ff', icon: '📑' },
            { label: 'Blood Group', val: profile?.blood_type || '—', color: '#ef4444', bg: '#fef2f2', icon: '🩸' },
            { label: 'Registry Status', val: profile?.verification_status || 'Unverified', color: '#10b981', bg: '#ecfdf5', icon: '✅' },
          ].map((item, index) => (
            <div key={item.label} className="stat-card animate-slide-up" style={{ 
              animationDelay: `${index * 0.1}s`,
              background: 'white',
              boxShadow: 'var(--shadow-premium)',
              border: 'none',
              padding: '1.5rem',
              display: 'flex',
              alignItems: 'center',
              gap: '1.25rem',
              borderRadius: '20px'
            }}>
              <div style={{ width: '60px', height: '60px', borderRadius: '16px', background: item.bg, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.8rem', flexShrink: 0 }}>
                {item.icon}
              </div>
              <div style={{ textAlign: 'left' }}>
                <div style={{ fontSize: '0.75rem', fontWeight: 800, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '0.25rem' }}>{item.label}</div>
                <div style={{ color: item.color, fontSize: '1.8rem', fontWeight: 900, lineHeight: 1 }}>{item.val}</div>
              </div>
            </div>
          ))}
        </div>



        <div className="grid-2 animate-slide-up" style={{ animationDelay: '0.5s' }}>
          <div className="card">
            <h4 className="mb-4" style={{ display: 'flex', alignItems: 'center', gap: '8px' }}><span>🩺</span> Medical Profile</h4>
            {profile ? (
              <div style={{ display: 'grid', gap: '1rem' }}>
                {[
                  ['Full Name', profile.full_name, '👤', '#fff7ed'],
                  ['Age', profile.age, '📅', '#eef2ff'],
                  ['Location', profile.location, '📍', '#ecfdf5'],
                  ['Donating Organ', profile.organ_to_donate, '🩸', '#fef2f2'],
                ].map(([k, v, icon, bg]) => (
                  <div key={k} style={{ display: 'flex', alignItems: 'center', padding: '1rem 1.25rem', background: '#f8fafc', borderRadius: '16px', border: '1px solid #e2e8f0', transition: 'transform 0.2s', cursor: 'default' }} onMouseOver={(e) => e.currentTarget.style.transform = 'translateY(-2px)'} onMouseOut={(e) => e.currentTarget.style.transform = 'translateY(0)'}>
                    <div style={{ width: '45px', height: '45px', borderRadius: '12px', background: bg, display: 'flex', alignItems: 'center', justifyContent: 'center', marginRight: '1.25rem', fontSize: '1.2rem', boxShadow: '0 2px 8px rgba(0,0,0,0.04)' }}>
                      {icon}
                    </div>
                    <div style={{ flex: 1 }}>
                      <div style={{ fontSize: '0.75rem', fontWeight: 700, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '0.2rem' }}>{k}</div>
                      <div style={{ fontWeight: 800, color: '#0f172a', fontSize: '1.05rem' }}>{v}</div>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="text-center" style={{ padding: '2rem' }}>
                <p className="text-muted">No profile data encrypted yet.</p>
              </div>
            )}
          </div>

          <div className="card" id="reports-section">
            <h4 className="mb-4">Medical Reports</h4>
            <UploadReport organ={profile?.organ_to_donate} onSuccess={() => api.get('/donor/reports').then(r => setReports(r.data))} />
            {reports.length > 0 && (
              <div className="mt-4">
                <p className="text-xs font-bold uppercase mb-2">History</p>
                {reports.slice(-2).map(r => (
                  <div key={r.id} style={{ display: 'flex', justifyContent: 'space-between', padding: '0.5rem', background: '#f9fafb', border: '1px solid #eee', borderRadius: '4px', marginBottom: '0.5rem' }}>
                     <span className="text-sm">Report #{r.id.substring(0,8).toUpperCase()}</span>
                     <span className={`badge ${r.status === 'Verified' ? 'badge-success' : 'badge-error'}`}>{r.status}</span>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        {matches.length > 0 && (
          <div style={{ marginTop: '2.5rem' }} id="matches-section">
            <h3 className="mb-4">Compatibility Matches</h3>
            <div style={{ display: 'grid', gap: '1rem' }}>
              {matches.map(m => (
                <div key={m.id} className="card" style={{ borderLeft: '6px solid var(--primary)' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                     <div>
                       <div style={{ display: 'flex', gap: '0.75rem', alignItems: 'center', marginBottom: '0.25rem' }}>
                          <h4 style={{ margin: 0, color: 'var(--primary)' }}>Match Record #{m.id.substring(0,8).toUpperCase()}</h4>
                          <span className={`badge ${m.risk_level === 'Low' ? 'badge-success' : m.risk_level === 'Medium' ? 'badge-warning' : 'badge-error'}`} style={{ fontSize: '0.65rem' }}>Risk: {m.risk_level}</span>
                       </div>
                       <p className="text-sm">Patient: <strong>{m.recipient_name}</strong></p>
                     </div>
                    <div style={{ textAlign: 'center' }}>
                      <div style={{ fontSize: '1.5rem', fontWeight: 800 }}>{m.match_score}%</div>
                      <span className="text-xs text-muted">Compatibility</span>
                    </div>
                  </div>
                  
                  <div style={{ marginTop: '1.5rem', display: 'flex', gap: '1rem' }}>
                    <button className="btn btn-primary" onClick={() => downloadReport(m)}>Download Report</button>
                    <button className="btn btn-outline" onClick={() => setSelectedMatch(m)}>View Protocol</button>
                    <div style={{ marginLeft: 'auto' }}>
                       <span className={`badge ${m.status === 'Hospital Approved' ? 'badge-success' : 'badge-neutral'}`}>{m.status}</span>
                    </div>
                  </div>
                  
                  <div style={{ marginTop: '1.5rem', borderTop: '1px solid #eee', paddingTop: '1rem' }}>
                    <StatusTimeline status={m.status} />
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        <Modal isOpen={!!selectedMatch} onClose={() => setSelectedMatch(null)} title="Match Documentation">
          {selectedMatch && (
            <div>
              <div className="alert alert-success" style={{ marginBottom: '1.5rem', border: '1px solid #10b981', background: '#ecfdf5' }}>
                <strong style={{ display: 'block', fontSize: '1.1rem', marginBottom: '0.25rem' }}>Protocol Verified:</strong> 
                Clinical match criteria satisfied. System-validated recipient review complete.
              </div>

              <div className="card" style={{ background: '#ffffff', padding: '1.25rem', marginBottom: '1rem', border: '1px solid #e5e7eb', boxShadow: '0 2px 4px rgba(0,0,0,0.05)', borderRadius: '12px' }}>
                 <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.75rem' }}>
                   <span className="text-sm"><strong>Match Score:</strong> <span style={{ color: 'var(--primary)', fontWeight: 'bold' }}>{selectedMatch.match_score}%</span></span>
                   <span className="text-sm"><strong>Risk Level:</strong> <span className={`badge ${selectedMatch.risk_level === 'Low' ? 'badge-success' : selectedMatch.risk_level === 'Medium' ? 'badge-warning' : 'badge-error'}`}>{selectedMatch.risk_level}</span></span>
                 </div>
                 <p className="text-sm" style={{ whiteSpace: 'pre-wrap', lineHeight: '1.6' }}>
                   <strong>Rationale:</strong> {selectedMatch.explanation?.split('\n\n')[0] || "Clinical match verified by system protocols."}
                 </p>
              </div>

              {selectedMatch.explanation?.includes('Recipient Review Protocol Verified:') && (
                <div className="card" style={{ background: '#f9fafb', padding: '1.25rem', marginBottom: '1rem', border: '1px solid #e5e7eb', borderRadius: '12px' }}>
                  <h5 style={{ marginTop: 0, marginBottom: '1rem', color: '#374151', fontSize: '0.9rem', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Recipient Review Protocol</h5>
                  <div style={{ display: 'grid', gap: '0.6rem' }}>
                    {selectedMatch.explanation.split('Recipient Review Protocol Verified:')[1].trim().split('\n').map((step, idx) => (
                      <div key={idx} style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', fontSize: '0.8rem' }}>
                        <div style={{ width: '16px', height: '16px', borderRadius: '50%', background: step.includes('Verified') ? '#d1fae5' : '#fee2e2', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                          <span style={{ color: step.includes('Verified') ? '#059669' : '#dc2626', fontSize: '0.6rem' }}>{step.includes('Verified') ? '✓' : '!'}</span>
                        </div>
                        <span style={{ color: '#4b5563' }}>{step.replace(/^\d\.\s/, '')}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              <div className="grid-2 mb-4">
                <div className="card" style={{ padding: '0.8rem', background: '#f9fafb', borderRadius: '8px' }}>
                  <p className="text-xs font-bold uppercase text-muted mb-1">Donor Details</p>
                  <p className="text-sm"><strong>Organ:</strong> {selectedMatch.donor_organ}</p>
                  <p className="text-sm"><strong>Blood Group:</strong> {selectedMatch.donor_blood_type}</p>
                </div>
                <div className="card" style={{ padding: '0.8rem', background: '#f9fafb', borderRadius: '8px' }}>
                  <p className="text-xs font-bold uppercase text-muted mb-1">Recipient Details</p>
                  <p className="text-sm"><strong>Registry ID:</strong> #R-{selectedMatch.recipient_id.substring(0,8).toUpperCase()}</p>
                  <p className="text-sm"><strong>Assigned:</strong> {selectedMatch.recipient_name}</p>
                </div>
              </div>

              {['Hospital Approved', 'In Progress', 'Completed'].includes(selectedMatch.status) ? (
                <div className="alert alert-success" style={{ background: '#f0fdf4' }}>
                   <p>Contact Authorized: <strong>{selectedMatch.recipient_email || "hospital-registry@org.match"}</strong></p>
                </div>
              ) : (
                <div className="alert alert-warning" style={{ textAlign: 'center' }}>Details restricted pending hospital approval.</div>
              )}
            </div>
          )}
        </Modal>

      </main>
    </div>
  );
}

function UploadReport({ organ, onSuccess }) {
  const [file, setFile] = useState(null);
  const [uploading, setUploading] = useState(false);
  const [message, setMessage] = useState('');

  const handleUpload = async (e) => {
    e.preventDefault();
    if (!file) return;
    setUploading(true);
    const fd = new FormData();
    fd.append('file', file);
    if (organ) fd.append('organ', organ);
    fd.append('report_type', 'General Medical Report');
    try {
      await api.post('/donor/upload-report', fd);
      setMessage('✅ Uploaded successfully!');
      setFile(null);
      onSuccess();
    } catch (err) {
      setMessage('❌ Upload failed: ' + (err.response?.data?.error || 'Unknown error'));
    } finally { setUploading(false); }
  };

  return (
    <form onSubmit={handleUpload}>
      <div className="upload-zone" onClick={() => document.getElementById('donor-file').click()}>
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" style={{ width: 40, height: 40, margin: '0 auto 1rem', display: 'block' }}><path d="M4 16l4-4 4 4 8-8"/></svg>
        <p style={{ fontWeight: 600, color: 'var(--text-main)' }}>{file ? file.name : 'Click to upload PDF'}</p>
        <p className="text-xs" style={{ color: 'var(--text-muted)', marginTop: '0.5rem' }}>Max file size 16MB</p>
      </div>
      <input id="donor-file" type="file" hidden accept=".pdf"
        onChange={e => setFile(e.target.files[0])} />
      {file && <button type="submit" className="btn btn-primary mt-2 w-full" disabled={uploading}>{uploading ? 'Uploading...' : 'Upload Report'}</button>}
      {message && <p className="text-sm mt-1">{message}</p>}
    </form>
  );
}
