import { useState, useEffect } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import Sidebar from '../../components/Sidebar';
import StatusTimeline from '../../components/StatusTimeline';
import Modal from '../../components/Modal';
import api from '../../services/api';
import PaymentModal from '../../components/PaymentModal';

export default function RecipientDashboard() {
  const { user } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  const [profile, setProfile] = useState(null);
  const [matches, setMatches] = useState([]);
  const [reports, setReports] = useState([]);
  const [selectedMatch, setSelectedMatch] = useState(null);
  const [loading, setLoading] = useState(true);
  const [showVerificationPayment, setShowVerificationPayment] = useState(false);
  const [showTransportPayment, setShowTransportPayment] = useState(false);
  const [activeTransportMatch, setActiveTransportMatch] = useState(null);

  useEffect(() => {
    const path = location.pathname.split('/').pop();
    if (path === 'reports') {
      document.getElementById('reports-section')?.scrollIntoView({ behavior: 'smooth' });
    } else if (path === 'matches') {
      document.getElementById('matches-section')?.scrollIntoView({ behavior: 'smooth' });
    }
  }, [location.pathname, loading]);

  useEffect(() => {
    Promise.all([
      api.get('/recipient/profile').catch(() => ({ data: null })),
      api.get('/matches/my-matches').catch(() => ({ data: [] })),
      api.get('/recipient/reports').catch(() => ({ data: [] })),
    ]).then(([p, m, r]) => {
      setProfile(p.data); setMatches(m.data); setReports(r.data);
    }).finally(() => setLoading(false));
  }, []);

  if (loading) return <div className="dashboard-layout"><Sidebar /><div className="main-content"><div className="loading-spinner"><div className="spinner"></div><p>Loading...</p></div></div></div>;

  const downloadReport = (match) => {
    const m = match || selectedMatch;
    if (!m) return;

    const content = `====================================================
               CLINICAL MATCH REPORT
====================================================
Match Record ID: #${m.id}
Current Status: ${m.status}
Compatibility Score: ${m.match_score}%

RECIPIENT DETAILS:
-----------------
Name: ${profile?.full_name || 'N/A'}
Blood Type: ${profile?.blood_type || 'N/A'}
Organ Needed: ${profile?.organ_needed || 'N/A'}
Urgency Score: ${profile?.urgency || '0'}/10

DONOR DETAILS:
-------------
Donor ID: #D-${m.id}
Name: ${m.donor_name || 'Restricted Phase'}
Contact: ${['Hospital Approved', 'In Progress', 'Completed'].includes(m.status) ? (m.donor_email || 'hospital-registry@org.match') : 'Restricted pending hospital approval.'}

ADDITIONAL MATCH DATA:
---------------------
Match Created At: ${m.created_at ? new Date(m.created_at).toLocaleString() : 'N/A'}
Last Updated At: ${m.updated_at ? new Date(m.updated_at).toLocaleString() : 'N/A'}
Match Rationale: ${m.explanation || 'Determined by protocol.'}

This document is officially generated by the OrganMatch Registry System.
====================================================`;

    const dataStr = "data:text/plain;charset=utf-8," + encodeURIComponent(content);
    const downloadAnchorNode = document.createElement('a');
    downloadAnchorNode.setAttribute("href", dataStr);
    downloadAnchorNode.setAttribute("download", `Recipient_Match_Report_${m.id}.txt`);
    document.body.appendChild(downloadAnchorNode);
    downloadAnchorNode.click();
    downloadAnchorNode.remove();
  };

  if (profile && !profile.is_paid) return (
    <div className="dashboard-layout"><Sidebar />
      <main className="main-content">
        <div style={{ maxWidth: '600px', margin: '4rem auto', textAlign: 'center' }}>
          <div className="card" style={{ padding: '3rem' }}>
            <div style={{ fontSize: '4rem', marginBottom: '1.5rem' }}>📑</div>
            <h2 className="mb-2">Report Verification Fee Required</h2>
            <p className="text-muted mb-6">To submit your clinical data for hospital review and enter the matching registry, a one-time verification fee of <strong>₹500</strong> is required.</p>
            <button className="btn btn-primary w-full" style={{ padding: '1rem' }} onClick={() => setShowVerificationPayment(true)}>Pay Verification Fee</button>
          </div>
        </div>
        <PaymentModal isOpen={showVerificationPayment} onClose={() => setShowVerificationPayment(false)} onSuccess={() => api.get('/recipient/profile').then(res => setProfile(res.data))} amount={500} purpose="Clinical Report Verification Fee" />
      </main>
    </div>
  );

  const handleTransportSuccess = () => {
    api.get('/matches/my-matches').then(res => setMatches(res.data));
  };

  return (
    <div className="dashboard-layout">
      <Sidebar />
      <main className="main-content">
        <div className="topbar">
          <div>
            <h1 style={{ color: 'var(--primary)' }}>Recipient Dashboard</h1>
            <p className="text-muted">Clinical Registry & Match Status — ID: <strong>#{user?.id}</strong></p>
          </div>
          {/* Edit Profile Button Removed as requested */}
        </div>

        {!profile && (
          <div className="alert alert-error">
             <h4 style={{ margin: 0 }}>Action Required: Register Now</h4>
             <p className="text-sm">Please complete your patient registration to enter the transplant queue.</p>
             <button className="btn btn-sm btn-primary" style={{ marginTop: '1rem' }} onClick={() => navigate('/recipient/register')}>Complete Setup</button>
          </div>
        )}

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '1.5rem', marginBottom: '3rem' }}>
          {[
            { label: 'Active Matches', val: matches.length, color: 'var(--secondary)', icon: '🤝' },
            { label: 'Lab Records', val: reports.length, color: '#6366f1', icon: '📑' },
            { label: 'Urgency Score', val: profile?.urgency ? `${profile.urgency}/10` : '—', color: '#ef4444', icon: '🏥' },
            { label: 'Registry Status', val: profile?.verification_status || 'Unverified', color: '#10b981', icon: '✅' },
          ].map((item, index) => (
            <div key={item.label} className="stat-card animate-slide-up" style={{ 
              animationDelay: `${index * 0.1}s`,
              background: 'white',
              boxShadow: 'var(--shadow-premium)',
              border: 'none',
              padding: '2.5rem',
              textAlign: 'center',
              borderRadius: '24px'
            }}>
              <div style={{ fontSize: '2rem', marginBottom: '1.5rem' }}>{item.icon}</div>
              <div style={{ fontSize: '0.75rem', fontWeight: 800, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: '0.5rem' }}>{item.label}</div>
              <div style={{ color: item.color, fontSize: '2.4rem', fontWeight: 1000 }}>{item.val}</div>
            </div>
          ))}
        </div>

        <div className="grid-2 animate-slide-up" style={{ animationDelay: '0.5s' }}>
          <div className="card">
            <h4 className="mb-4" style={{ display: 'flex', alignItems: 'center', gap: '8px' }}><span>👤</span> Patient Profile</h4>
            {profile ? (
              <div style={{ display: 'grid', gap: '1rem' }}>
                {[
                  ['Full Name', profile.full_name, '📝'],
                  ['Age', profile.age, '📅'],
                  ['Blood Type', profile.blood_type, '🩸'],
                  ['Organ Needed', profile.organ_needed, '🏥'],
                ].map(([k, v, icon]) => (
                  <div key={k} style={{ display: 'flex', justifyContent: 'space-between', padding: '1rem', background: '#f8fafc', borderRadius: '12px', border: '1px solid rgba(0,0,0,0.02)' }}>
                    <span style={{ fontWeight: 600, color: '#64748b', display: 'flex', alignItems: 'center', gap: '8px' }}><span>{icon}</span> {k}</span>
                    <span style={{ fontWeight: 800, color: 'var(--text-main)' }}>{v}</span>
                  </div>
                ))}
              </div>
            ) : (
              <div className="text-center" style={{ padding: '2rem' }}>
                <p className="text-muted">No patient record found.</p>
              </div>
            )}
          </div>

          <div className="card" id="reports-section">
            <h4 className="mb-4">Medical Records</h4>
            <RecipientUpload organ={profile?.organ_needed} onSuccess={() => api.get('/recipient/reports').then(r => setReports(r.data))} />
            <div className="mt-4">
              <p className="text-xs font-bold uppercase mb-2">History</p>
              {reports.slice(-2).map(r => (
                <div key={r.id} style={{ display: 'flex', justifyContent: 'space-between', padding: '0.5rem', background: '#f9fafb', border: '1px solid #eee', borderRadius: '4px', marginBottom: '0.5rem' }}>
                   <span className="text-sm">Lab Report #{r.id.substring(0,8).toUpperCase()}</span>
                   <span className={`badge ${r.status === 'Verified' ? 'badge-success' : 'badge-error'}`}>{r.status}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {matches.length > 0 && (
          <div style={{ marginTop: '2.5rem' }} id="matches-section">
            <h3 className="mb-4">Compatibility Matches</h3>
            <div style={{ display: 'grid', gap: '1rem' }}>
              {matches.map(m => (
                <div key={m.id} className="card" style={{ borderLeft: '6px solid var(--secondary)' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
                     <div>
                       <div style={{ display: 'flex', gap: '0.75rem', alignItems: 'center', marginBottom: '0.25rem' }}>
                          <h4 style={{ margin: 0, color: 'var(--secondary)' }}>Compatible Donor ID: #D-{m.id.substring(0,8).toUpperCase()}</h4>
                          <span className={`badge ${m.risk_level === 'Low' ? 'badge-success' : m.risk_level === 'Medium' ? 'badge-warning' : 'badge-error'}`} style={{ fontSize: '0.65rem' }}>Risk: {m.risk_level}</span>
                       </div>
                       <p className="text-sm">Donor: <strong>{m.donor_name}</strong></p>
                     </div>
                    <div style={{ textAlign: 'center' }}>
                      <div style={{ fontSize: '1.5rem', fontWeight: 800, color: 'var(--secondary)' }}>{m.match_score}%</div>
                      <span className="text-xs text-muted">Compatibility</span>
                    </div>
                  </div>
                  
                    <div className="flex justify-between items-center" style={{ marginTop: '1.5rem' }}>
                      <div className="flex gap-2">
                        {(m.status === 'Hospital Approved' || m.status?.includes('Approved')) && !m.is_transport_paid ? (
                          <button className="btn btn-primary" onClick={() => { setActiveTransportMatch(m); setShowTransportPayment(true); }}>
                            Pay Organ Transport Fee (₹15,000)
                          </button>
                        ) : (
                          <>
                            <button className="btn btn-success" onClick={() => setSelectedMatch(m)}>Review Protocol</button>
                            <button className="btn btn-outline" onClick={() => downloadReport(m)}>Download Report</button>
                          </>
                        )}
                      </div>
                      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '0.25rem' }}>
                        <span className={`badge ${m.status === 'Hospital Approved' ? 'badge-success' : 'badge-neutral'}`}>{m.status}</span>
                        {m.status === 'Hospital Approved' && (
                          <span className={`badge ${m.is_transport_paid ? 'badge-success' : 'badge-warning'}`} style={{ fontSize: '0.6rem' }}>
                            {m.is_transport_paid ? 'Transport Paid' : 'Transport Payment Pending'}
                          </span>
                        )}
                      </div>
                    </div>
                  
                  <div style={{ marginTop: '2rem', borderTop: '1px solid #eee', paddingTop: '1.5rem' }}>
                    <StatusTimeline status={m.status} />
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        <Modal isOpen={!!selectedMatch} onClose={() => setSelectedMatch(null)} title="Match Documentation">
          {selectedMatch && (
            <div>
              <div className="alert alert-success" style={{ marginBottom: '1.5rem', border: '1px solid #10b981', background: '#ecfdf5' }}>
                <strong style={{ display: 'block', fontSize: '1.1rem', marginBottom: '0.25rem' }}>Protocol Verified:</strong> 
                Identical match criteria satisfied. All recipient-side clinical checks completed.
              </div>

              <div className="card" style={{ background: '#ffffff', padding: '1.25rem', marginBottom: '1rem', border: '1px solid #e5e7eb', boxShadow: '0 2px 4px rgba(0,0,0,0.05)', borderRadius: '12px' }}>
                 <h5 style={{ marginTop: 0, marginBottom: '0.75rem', color: 'var(--primary)' }}>Clinical Rationale</h5>
                 <p className="text-sm" style={{ lineHeight: '1.6', whiteSpace: 'pre-wrap' }}>
                   {selectedMatch.explanation?.split('\n\n')[0] || "Match determined by blood-group compatibility and regional priority levels."}
                 </p>
              </div>

              {selectedMatch.explanation?.includes('Recipient Review Protocol Verified:') && (
                <div className="card" style={{ background: '#f9fafb', padding: '1.25rem', marginBottom: '1.5rem', border: '1px solid #e5e7eb', borderRadius: '12px' }}>
                  <h5 style={{ marginTop: 0, marginBottom: '1rem', color: '#374151', fontSize: '0.9rem', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Recipient Review Protocol</h5>
                  <div style={{ display: 'grid', gap: '0.75rem' }}>
                    {selectedMatch.explanation.split('Recipient Review Protocol Verified:')[1].trim().split('\n').map((step, idx) => (
                      <div key={idx} style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', fontSize: '0.85rem' }}>
                        <div style={{ width: '18px', height: '18px', borderRadius: '50%', background: step.includes('Verified') ? '#d1fae5' : '#fee2e2', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                          <span style={{ color: step.includes('Verified') ? '#059669' : '#dc2626', fontSize: '0.7rem' }}>{step.includes('Verified') ? '✓' : '!'}</span>
                        </div>
                        <span style={{ color: '#4b5563' }}>{step.replace(/^\d\.\s/, '')}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              <div className="grid-2 mb-4">
                <div className="card" style={{ padding: '0.8rem', background: '#f9fafb', borderRadius: '8px' }}>
                  <p className="text-xs font-bold uppercase text-muted mb-1">Donor Details</p>
                  <p className="text-sm"><strong>Registry ID:</strong> #D-{selectedMatch.donor_id?.substring ? selectedMatch.donor_id.substring(0,8).toUpperCase() : (selectedMatch.donor_id?.id || selectedMatch.donor_id).toString().substring(0,8).toUpperCase()}</p>
                  <p className="text-sm"><strong>Assigned:</strong> {selectedMatch.donor_name}</p>
                </div>
                <div className="card" style={{ padding: '0.8rem', background: '#f9fafb', borderRadius: '8px' }}>
                  <p className="text-xs font-bold uppercase text-muted mb-1">Recipient Details</p>
                  <p className="text-sm"><strong>Organ:</strong> {selectedMatch.recipient_organ}</p>
                  <p className="text-sm"><strong>Blood Group:</strong> {selectedMatch.recipient_blood_type}</p>
                </div>
              </div>

              {['Hospital Approved', 'In Progress', 'Completed'].includes(selectedMatch.status) ? (
                <div className="alert alert-success" style={{ background: '#f0fdf4', border: '1px solid #bbf7d0', textAlign: 'center' }}>
                   Authorized Clinical Data: <strong style={{ color: '#166534' }}>{selectedMatch.donor_email || "hospital-registry@org.match"}</strong>
                </div>
              ) : (
                <div className="alert alert-warning" style={{ background: '#fffbeb', border: '1px solid #fde68a', textAlign: 'center' }}>
                   <p className="font-bold">Administrative Review In Progress</p>
                   <p className="text-xs">Contact details restricted until hospital approval.</p>
                </div>
              )}
            </div>
          )}
        </Modal>

      </main>
      <PaymentModal isOpen={showTransportPayment} onClose={() => { setShowTransportPayment(false); setActiveTransportMatch(null); }} 
                    onSuccess={handleTransportSuccess} amount={15000} purpose="Organ Transport & Preservation Fee" 
                    match_id={activeTransportMatch?.id} />
    </div>
  );
}

function RecipientUpload({ organ, onSuccess }) {
  const [file, setFile] = useState(null);
  const [uploading, setUploading] = useState(false);
  const [msg, setMsg] = useState('');

  const handleUpload = async (e) => {
    e.preventDefault();
    if (!file) return;
    setUploading(true);
    const fd = new FormData();
    fd.append('file', file);
    if (organ) fd.append('organ', organ);
    fd.append('report_type', 'General Medical Report');
    try {
      await api.post('/recipient/upload-report', fd);
      setMsg('✅ Uploaded!'); setFile(null); onSuccess();
    } catch (err) { setMsg('❌ ' + (err.response?.data?.error || 'Failed')); }
    finally { setUploading(false); }
  };

  return (
    <form onSubmit={handleUpload}>
      <div className="upload-zone" onClick={() => document.getElementById('rec-file').click()}>
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" style={{ width: 40, height: 40 }}><path d="M4 16l4-4 4 4 8-8"/></svg>
        <p className="text-sm">{file ? file.name : 'Upload PDF'}</p>
      </div>
      <input id="rec-file" type="file" hidden accept=".pdf" onChange={e => setFile(e.target.files[0])} />
      {file && <button type="submit" className="btn btn-primary mt-2 w-full" disabled={uploading}>{uploading ? 'Uploading...' : 'Upload'}</button>}
      {msg && <p className="text-xs mt-1">{msg}</p>}
    </form>
  );
}
